#!/bin/bash -l
#SBATCH --account=PHY20032
#SBATCH --partition=development
#SBATCH --job-name=SiO2
#SBATCH --nodes=1
#SBATCH --ntasks=56
#SBATCH --time=01:30:00
#SBATCH --mail-user=krishnaa.vadivel@yale.edu
#SBATCH --mail-type=ALL

./link_script.sh
module load impi
data-file2kgrid.py --kgrid 2 2 2 --kshift 0.0 0.0 0.0 --qshift 0.0 0.0 0.001 ./tmp/SiO2.xml kgrid.inp
ibrun kgrid.x kgrid.inp kgrid.out kgrid.log
python copy_kgrid.py
rm slurm*
