#!/bin/bash -l
#SBATCH --account=PHY20032
#SBATCH --partition=development
#SBATCH --job-name=SiO2
#SBATCH --nodes=1
#SBATCH --ntasks=56
#SBATCH --time=01:30:00
#SBATCH --mail-user=krishnaa.vadivel@yale.edu
#SBATCH --mail-type=ALL

./link_script.sh
module load impi
module load espresso 
ibrun pw2bgw.x < pw2bgw.in &> pw2bgw.out
cp ./tmp/WFN ./WFN
cp ./tmp/VSC ./VSC
cp ./tmp/VKB ./VKB

# If no parabands, run below. Else, comment out.
#wfn2hdf.x BIN WFN WFN.h5
